version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=${postgres-username}
      - POSTGRES_PASSWORD=${postgres-pass}
      - POSTGRES_DB=notes
    ports:
      - '5432:5432'

  notes:
    container_name: notes_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/notes
      - SPRING_DATASOURCE_USERNAME=${postgres-username}
      - SPRING_DATASOURCE_PASSWORD=${postgres-pass}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - psql-db