runtime: java17
instance_class: F2
handlers:
- url: /css
  static_dir: src/main/resources/static/css
- url: /js
  static_dir: src/main/resources/static/js
- url: /jquery-ui
  static_dir: src/main/resources/static/jquery-ui
- url: /dist
  static_dir: src/main/resources/static/dist
- url: /.*
  script: auto
  secure: always
#  http_headers:
#    Access-Control-Allow-Origin: https://noteapp-399113.lm.r.appspot.com
#  redirect_http_response_code: 301